export const Constantes = {
    iniciar_sesion: 'Iniciar Sesión',
    bienvenido: 'Bienvenido',
    tornillos: 'Tornillos',
    por_revisar: 'por revisar',
    revisar: 'Revisar',
    nombre: 'Nombre',
    precio: 'Precio',
    formato: 'Formato',
    marca: 'Marca',
    acciones: 'Acciones',
    mostrando: 'Mostrando',
    a: 'a',
    de: 'de',
    items: 'ítems',
    anadir_producto: 'Añadir producto',
    nuevo_producto: 'Nuevo producto',
    cancelar: 'Cancelar',
    guardar: 'Guardar',
    seleccione_valor: 'Seleccione un valor',
    confirmacion: 'Confirmación',
    eliminar: 'Eliminar',
    desea_eliminar: '¿Desea eliminar el elemento seleccionado?'
}